default = "bing"
 #browser = "/mnt/c/Program Files/Mozilla Firefox/firefox.exe"
browser = "/mnt/c/Users/Alastair.Montgomery/AppData/Local/Mozilla Firefox/firefox.exe"
bing = "https://bing.com/search?q="
brave = "https://search.brave.com/search?q="
duckduck = "https://duckduckgo.com/?q="
ecosia = "https://www.ecosia.org/search?q="
gmaps = "https://www.google.com/maps/place/"
google = "https://www.google.com/search?q="
searx = "https://searx.org/search?q="
startpage = "https://www.startpage.com/sp/search?q="
wiki = "https://en.wikipedia.org/wiki/Special:Search?go=Go&search="
